### ISSUE TITLE
Revisión General de Sprint

### ISSUE THREAD

**Issue by aranorj** [pedroZarza/repoML-deploy#3]
Header:
- [ ] Logo

- [ ]  Barra de búsqueda
- [ ] Comprá en cuotas y sin tarjeta de crédito
- [ ] Barra de navegación:
- [x] Ofertas
- [ ] Tiendas Oficiales
- [ ] Vender
- [x] Ayuda
- [ ] Login
- [ ] Registro
- [ ] Mis compras

Main:

- [ ] Sección basada en las últimas visitas
- [ ] Sección de ofertas

**Comment by aranorj** [comment]
Ya esta listas las secciones ofertas y ayuda

**Comment by aranorj** [comment]
Por qué no veo un filtro de productos?

**Comment by pedroZarza** [comment]
porque no lo hice :)

**Comment by pedroZarza** [comment]
> Por qué no veo un filtro de productos?

aca te respondo

**Comment by aranorj** [comment]
Ok, aprobado.
